### ISSUE TITLE
Throws: Undefined is not a Function

### ISSUE THREAD

**Issue by chrisalexander55** [przeor/React-Native-example-FLUX-starter-kit-for-ios#3]
![screen shot 2015-05-09 at 3 45 56 pm](https://cloud.githubusercontent.com/assets/1727612/7551751/973b3496-f662-11e4-9bb0-3a2e8d3be631.png)

FYI... Per the spec (http://www.html5rocks.com/en/tutorials/es6/promises/#toc-api), No static or instance methods called .done().

**Comment by przeor** [comment]
fixed by @chrisalexander55 https://github.com/przeor/React-Native-example-FLUX-starter-kit-for-ios/commit/fa2921e9d55af867e7d518845c263beac683cf31
